// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.
import {Lane} from "./Interfaces.sol";

interface IControllerV1 {

    error BadSetting(bytes32 field);
    error NotBuyOnly();
    error NotForSale();
    error OnlyOwner();
    error Reentrant();
    error Underpaid();

    event Bought(uint256 indexed sid, address indexed buyer, uint256 price);
    event BuyOnlySet(bool buyOnly);
    event FloorBpsSet(uint16 floorBps);
    event StartBpsSet(uint16 startBps);
    event StepBpsSet(uint16 stepBps);
    event StepEverySet(uint32 stepEvery);

    function CORE() external view returns (address);
    function buy(uint256 sid) external payable;
    function buyOnly() external view returns (bool);
    function floorBps() external view returns (uint16);
    function nextOverprint() external pure returns (bool, uint256, uint256);
    function nextPage(Lane lane) external view returns (bool ready, uint256[80] memory ids, uint8 format);
    function priceOf(uint256 sid) external view returns (uint256);
    function setBuyOnly(bool on) external;
    function setFloorBps(uint16 v) external;
    function setStartBps(uint16 v) external;
    function setStepBps(uint16 v) external;
    function setStepEvery(uint32 v) external;
    function startBps() external view returns (uint16);
    function statementPrice(uint256, uint256 cost, uint64 listedAt) external view returns (uint256);
    function stepBps() external view returns (uint16);
    function stepEvery() external view returns (uint32);
    function wants(uint256) external pure returns (uint16);
}
