// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.
import {Lane} from "./Interfaces.sol";

interface ICoreLens {
    struct Snapshot {
        uint256 ethRate;
        uint256 ethPrice;
        uint256 averageBid;
        uint256 hourlyRoom;
        uint256 ethPileSize;
        uint256 ethPileHead;
        uint256 exitPileSize;
        uint256 exitPileHead;
        bool ethPageReady;
        bool exitPageReady;
        uint256 ethPot;
        uint256 ethToBuyback;
        uint256 xPot;
        uint256 xToBuyback;
        uint256 unbookedEth;
        uint256 salesOwed;
        uint256 routerBalance;
        uint256 routerOwed;
        uint256 flushToCore;
        uint256 flushToPayees;
        address controller;
        address successor;
        bool controllerLocked;
        bool exitModuleLocked;
        bool targetsLocked;
        bool successorLocked;
        StatementView[] statements;
    }

    struct StatementView {
        uint256 id;
        Lane lane;
        uint256 cost;
        bool listed;
        uint256 auctionId;
        uint256 askingPrice;
        uint8 status;
        uint256 topBid;
        uint64 endTime;
    }

    function CORE() external view returns (address);
    function CREDITS() external view returns (address);
    function HOUSE() external view returns (address);
    function ROUTER() external view returns (address);
    function STATEMENTS() external view returns (address);
    function bidFor(uint256 id) external view returns (uint256);
    function controller() external view returns (address);
    function snapshot() external view returns (Snapshot memory s);
    function statementsPage(uint256 start, uint256 n) external view returns (StatementView[] memory);
}
