// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.
import {Lane, Settings} from "./Interfaces.sol";

interface ICore {
    enum StatementStatus {
        None,
        Held,
        Listed,
        Bid,
        Ended,
        Sold,
        Returned
    }

    error AboveCeiling();
    error AlreadyOwned();
    error AuctionLive();
    error BadAuction();
    error BadCost();
    error BadFormat();
    error BadModule();
    error BadOverprint();
    error BadPrice();
    error BadRate();
    error BadSender();
    error BadSetting(bytes32 field);
    error BadStack();
    error BadStatement();
    error BadSuccessor(address who);
    error BadSwap();
    error BelowFloor();
    error CallFailed();
    error DailyCap();
    error Empty();
    error ExitTokenChanged();
    error ForbiddenTarget();
    error HasBid();
    error Held();
    error HourlyCap();
    error InPile();
    error Locked(bytes32 what);
    error Measuring();
    error NoCode(address who);
    error NoCredit();
    error NoExitModule();
    error NoSuccessor();
    error NotHeld();
    error NotHolder();
    error NotInPile(uint256 id);
    error NotListed();
    error NotOwner();
    error NotReady();
    error NothingBought();
    error NothingToBuy();
    error OnlyController();
    error OnlyOwner();
    error OnlyPendingOwner();
    error OnlyPoolManager();
    error PotTooSmall();
    error Reentrancy();
    error Slippage();
    error TargetNotAllowed();
    error TooEarly();
    error TooSoon();
    error Underpaid();
    error ZeroAddress();
    error ZeroAmount();
    error ZeroId();

    event Buyback(address indexed caller, uint256 amountIn, uint256 tip);
    event CoinRescued(address indexed to, uint256 amount);
    event Composed(
        uint256 indexed sid, Lane lane, uint8 format, uint256 cost, uint256 reimbursement, address indexed caller
    );
    event ControllerLocked();
    event ControllerSet(address controller);
    event CreditBought(uint256 indexed id, address indexed from, Lane lane, uint256 cost);
    event EthRateFill(uint256 spent, uint256 rate, uint256 pot);
    event ExitBuyback(address indexed caller, uint256 slice, uint256 coinIn);
    event ExitModuleLocked();
    event ExitModuleSet(address exitModule, address exitToken, uint256 unitPerPoint);
    event ExitRateFill(uint256 rate, uint256 pot);
    event FeesAdded(uint256 amount);
    event ListingBought(
        uint256 indexed id, address indexed target, address indexed caller, uint256 cost, uint256 tip, uint256 rate
    );
    event Migrated(
        address indexed successor,
        uint256 eth,
        uint256 credits,
        uint256 statements,
        uint256 exitTokens,
        uint256 skippedStatements
    );
    event NftRescued(address indexed token, uint256 indexed id, address indexed to);
    event Overprinted(uint256 indexed baseId, uint256 indexed topId, uint256 cost);
    event OwnershipTransferStarted(address indexed owner, address indexed pending);
    event OwnershipTransferred(address indexed from, address indexed to);
    event RateSet(uint256 rate);
    event SalesCollected(uint256 amount, uint256 toBuyback);
    event SettingsSet(Settings settings);
    event Skimmed(uint256 eth, uint256 exitToken);
    event StatementExited(uint256 indexed sid, Lane lane, uint256 received);
    event StatementListed(uint256 indexed sid, uint256 indexed auctionId, uint256 reserve);
    event StatementRepriced(uint256 indexed sid, uint256 reserve);
    event StatementSold(uint256 indexed sid, uint256 indexed auctionId, address indexed holder);
    event StatementSoldTo(uint256 indexed sid, address indexed buyer, uint256 price);
    event SuccessorLocked();
    event SuccessorSet(address successor);
    event TargetAdded(address target);
    event TargetRemoved(address target);
    event TargetsLocked();
    event XRateSet(uint256 rate);

    receive() external payable;

    function AUCTION_FACTORY() external view returns (address);
    function COIN() external view returns (address);
    function ESCROW() external view returns (address);
    function FACTORY() external view returns (address);
    function FEE_SOURCE() external view returns (address);
    function HOOK() external view returns (address);
    function HOUSE() external view returns (address);
    function LOCKER() external view returns (address);
    function MANAGER() external view returns (address);
    function OVERPRINT_CAP_PER_DAY() external view returns (uint256);
    function POOL_FEE() external view returns (uint24);
    function RATE_START() external view returns (uint256);
    function SUPPLY() external view returns (uint256);
    function TICK_SPACING() external view returns (int24);
    function XRATE_START() external view returns (uint256);
    function acceptOwnership() external;
    function addTarget(address t) external;
    function allowedTarget(address) external view returns (bool);
    function buyListing(uint256 value, bytes memory data, uint256 id, address target) external;
    function buyback() external;
    function buybackExit(uint256 maxCoinIn) external;
    function ceilingOf(uint256 id) external view returns (uint256);
    function checkpointTime() external view returns (uint64);
    function collectSales() external;
    function compose() external;
    function composeExit() external;
    function controller() external view returns (address);
    function controllerLocked() external view returns (bool);
    function creditInfo(uint256 id) external view returns (bool inPile, Lane lane, uint256 cost, uint64 acquiredAt);
    function ethPot() external view returns (uint256);
    function ethPrice() external view returns (uint256 price);
    function ethRate() external view returns (uint256 read);
    function ethToBuyback() external view returns (uint256);
    function exitAuctionPrice() external view returns (uint256);
    function exitAuctionQuote() external view returns (uint256 slice, uint256 coinIn);
    function exitModule() external view returns (address);
    function exitModuleLocked() external view returns (bool);
    function exitStatement(uint256 sid) external;
    function exitToken() external view returns (address);
    function heldStatements() external view returns (uint256[] memory sids);
    function hourlyRoom() external view returns (uint256);
    function lastBuybackBlock() external view returns (uint256);
    function lastFillTime() external view returns (uint64);
    function lockController() external;
    function lockExitModule() external;
    function lockSuccessor() external;
    function lockTargets() external;
    function migrate(uint256, uint256) external;
    function onERC721Received(address, address, uint256, bytes memory) external view returns (bytes4);
    function overprint() external;
    function overprintCount() external view returns (uint256);
    function overprintDay() external view returns (uint256);
    function owner() external view returns (address);
    function pendingOwner() external view returns (address);
    function pileHead(Lane lane) external view returns (uint256);
    function pileNext(uint256 id) external view returns (uint256);
    function pilePage(Lane lane, uint256 startAfter, uint256 n) external view returns (uint256[] memory ids);
    function pileSize(Lane lane) external view returns (uint256);
    function rateAtCheckpoint() external view returns (uint256);
    function removeTarget(address target) external;
    function repriceStatement(uint256 sid) external;
    function rescueCoin(address, uint256) external;
    function rescueNft(address, uint256, address) external;
    function scoreOf(uint256 id) external view returns (uint256);
    function sellForEth(uint256[] memory ids, uint256 minOut) external;
    function sellForEth(uint256[] memory ids) external;
    function sellForExitToken(uint256[] memory ids) external;
    function sellForExitToken(uint256[] memory ids, uint256 minOut) external;
    function sellTo(uint256 sid, address buyer) external payable;
    function setController(address c) external;
    function setExitModule(address module) external;
    function setRate(uint256 rate) external;
    function setSettings(Settings memory) external;
    function setSuccessor(address) external;
    function setXRate(uint256 rate) external;
    function settings() external view returns (Settings memory);
    function skim() external;
    function statementInfo(uint256 sid) external view returns (bool held, Lane lane, uint256 cost, uint64 clockStart);
    function statementStatus(uint256 sid)
        external
        view
        returns (StatementStatus status, uint256 auctionId, uint256 reserve, uint256 bid, uint64 endTime);
    function successor() external view returns (address);
    function successorLocked() external view returns (bool);
    function syncStatement(uint256 sid) external;
    function targetsLocked() external view returns (bool);
    function transferOwnership(address to) external;
    function unitPerPoint() external view returns (uint256);
    function unlockCallback(bytes memory data) external returns (bytes memory);
    function xPot() external view returns (uint256);
    function xRate() external view returns (uint256 r);
    function xStartPrice() external view returns (uint256);
    function xStartTime() external view returns (uint64);
    function xToBuyback() external view returns (uint256);
}
