// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.
import {Settings} from "./Interfaces.sol";

interface ICoreLib {
    error BadSetting(bytes32 field);
    error BadSwap();

    event SettingsSet(Settings settings);

    function climb(
        uint256 r,
        uint256 cap,
        uint256 last,
        uint256 t,
        uint256 nowTs,
        uint256 base,
        uint256 maxBps,
        uint256 dbl
    ) external pure returns (uint256);
    function decay(uint256 start, uint256 elapsed, uint256 halfLife) external pure returns (uint256 p);
    function unpack(uint256 a, uint256 b, uint256 c) external pure returns (Settings memory s);

    function swapIn(address manager, address coin, uint24 fee, int24 spacing, address hook, uint256 amountIn)
        external
        returns (uint256 owed, uint256 bought);
}
