// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.
import {Lane, Settings} from "./Interfaces.sol";

interface ICoreLib {

    error BadSetting(bytes32 field);
    error BadSuccessor(address who);
    error BadSwap();
    error CallFailed();
    error Empty();
    error Held();
    error InPile();
    error Locked(bytes32 what);
    error NoCode(address who);
    error NoExitModule();
    error NoSuccessor();
    error NotHolder();
    error NotOwner();
    error OnlyOwner();
    error PotTooSmall();
    error Slippage();
    error ZeroAddress();
    error ZeroAmount();
    error ZeroId();

    event CreditAdopted(uint256 indexed id, uint256 cost);
    event CreditBought(uint256 indexed id, address indexed from, Lane lane, uint256 cost);
    event ExitRateFill(uint256 rate, uint256 pot);
    event Migrated(address indexed successor, uint256 eth, uint256 exitTokens, uint256 credits);
    event NftRescued(address indexed token, uint256 indexed id, address indexed to);
    event SettingsSet(Settings settings);
    event SuccessorLocked();
    event SuccessorSet(address successor);

    function climb(uint256 r, uint256 pot, uint256 anchorTime, uint256 t, uint256 nowTs)
        external
        view
        returns (uint256 price, uint256 read);
    function decay(uint256 start, uint256 elapsed, uint256 halfLife) external pure returns (uint256 p);
    function unpack(uint256 a, uint256 b, uint256 c) external pure returns (Settings memory s);

    function swapIn(address manager, address coin, uint24 fee, int24 spacing, address hook, uint256 amountIn)
        external
        returns (uint256 owed, uint256 bought);
}
