// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.

interface IFeeRouter {
    error FlushFailed();
    error IsLocked();
    error NoCode(address account);
    error NoEngine();
    error OnlyOwner();
    error OnlyPendingOwner();
    error Reentered();
    error ZeroAddress();

    event EngineSet(address indexed previous, address indexed engine);
    event Flushed(address indexed engine, uint256 amount);
    event Locked(address indexed engine);
    event OwnershipTransferStarted(address indexed owner, address indexed pendingOwner);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    receive() external payable;

    function acceptOwnership() external;
    function engine() external view returns (address);
    function flush() external;
    function lock() external;
    function locked() external view returns (bool);
    function owner() external view returns (address);
    function pendingOwner() external view returns (address);
    function setEngine(address engine_) external;
    function transferOwnership(address newOwner) external;
}
