# post processes `cast interface` output: shared types stay single definitions in Interfaces.sol, the Core enum
# (which the abi shows as uint8) is declared once inside ICore.
import re, sys
src = open(sys.argv[1]).read()
name = sys.argv[2]
lib = re.search(r"library (\w+) \{(.*?)\n\}\n\n", src, flags=re.S)
src = re.sub(r"library \w+ \{.*?\n\}\n\n", "", src, flags=re.S)
if name == "ICoreLens" and lib:
    # the structs of the lens are declared once inside its interface
    src = src.replace(lib.group(1) + ".", "")
    structs = lib.group(2).strip("\n")
    src = src.replace("interface ICoreLens {\n", "interface ICoreLens {\n" + structs + "\n\n", 1)
src = re.sub(r"\n    type Lane is uint8;\n", "\n", src)
for t in ("Settings", "Stack", "Sale"):
    src = re.sub(r"\n    struct %s \{.*?\n    \}\n" % t, "\n", src, flags=re.S)
src = src.replace("Core.StatementStatus", "StatementStatus")
src = src.replace("// SPDX-License-Identifier: UNLICENSED", "// SPDX-License-Identifier: MIT")
if name == "ICoreLib":
    # state changing library functions are not in the library abi: added from the source signatures, selectors are
    # pinned by test/BuildIdentity.t.sol against the artifact
    # setSettings is left out on purpose: a library selector names the struct (`setSettings(Settings)`)
    extra = ("\n    function swapIn(address manager, address coin, uint24 fee, int24 spacing, address hook, uint256 amountIn)\n"
             "        external\n        returns (uint256 owed, uint256 bought);\n")
    i = src.rstrip().rfind("}")
    src = src[:i] + extra + "}\n"
uses = [t for t in ("Lane", "Settings", "Stack", "Sale") if re.search(r"\b%s\b" % t, src)]
imp = 'import {%s} from "./Interfaces.sol";\n' % ", ".join(uses) if uses else ""
src = src.replace("pragma solidity ^0.8.28;\n", "pragma solidity ^0.8.28;\n\n// generated by script/tools/gen-interfaces.sh from the production abi. do not edit by hand.\n" + imp, 1)
if name == "ICore":
    enum = "\n    enum StatementStatus {\n        None,\n        Held,\n        Listed,\n        Bid,\n        Ended,\n        Sold,\n        Returned\n    }\n"
    src = src.replace("interface ICore {\n", "interface ICore {" + enum, 1)
src = re.sub(r"\{\n\n", "{\n", src)
src = re.sub(r"\n{3,}", "\n\n", src)
print(src, end="")
